repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        exclude: ^dist/
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        # entry: bash -c 'pylint "$@" || true' -- # Use this line to pass for now
        language: system
        types: [ python ]
        args:
          [
            "-rn", # Only display messages
            "--rcfile=pylintrc"
          ]
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: mypy
        verbose: true
        # entry: bash -c 'mypy "$@" || true' -- # Use this line to pass for now
        language: system
        types: [ python ]
        exclude: ^tests/
        args:
          [
            "--no-strict-optional",
            "--ignore-missing-imports"
          ]
